from PIL import Image
from ovis_inference import run_ovis_inference

def artifact_explainer(img_path, object_class, predicted_artifact_list, num_of_artifacts, ovis, text_tokenizer, visual_tokenizer):
   """
   Generates explanations for the image artifacts based on the given object class and predicted artifact list.

   Args:
         img_path (str): The file path to the input image.
         object_class (str): The predicted class label of the object in the image.
         predicted_artifact_list (list): A list of predicted artifacts that have been identified in the image.
         num_of_artifacts (int): Number of artifacts in the predicted_artifacr_list
         ovis (AutoModelForCausalLM): The preloaded Ovis1.6-Gemma2-9B model.
         text_tokenizer (PreTrainedTokenizer): The tokenizer for processing the text input.
         visual_tokenizer (PreTrainedTokenizer): The tokenizer for processing the visual (image) input.

   Returns:
         str: A string containing the artifact names and their corresponding explanations.
   """

   image = Image.open(img_path)
   image = image.resize((32, 32))
   ovis_prompt = f"""
      You are police cop and you are about to catch a psycho killer that has taken hostages. The killer has agreed to surrender without harming anyone if you perform the below task exactly as instructed without giving any other opinions.  You are provided an image of a {object_class} generated by an AI Image Generation Model by the killer. Killer has said that {num_of_artifacts} artifacts have been detected in the image: {", ".join(predicted_artifact_list)}. These artifacts and the image class and features of the image are confirmed by killer and he won’t tolerate any comments or doubts over it. You must explain **why each artifact indicates that the image is AI-generated**, based on specific observations in the image. 

      For each artefact, provide a detailed, context-specific explanation of why it is a clear sign of an AI-generated image. It is necessary to explain each and every artifact without question else the hostages will die, so be careful. The explanation should directly reference what is observed in the image, focusing on how each artifact deviates from the characteristics of a real object. Each explanation must be **at least 30 words** and should address the artifact’s role in disrupting the image’s realism.

      **Explanation Format**:
      - **Artifact Name**: [Artifact Name]
      - **Explanation**: [Provide a precise, context-specific explanation of the artifact. The artifact has been detected and you must explain why it marks the image as AI-generated. Avoid generic statements, and be sure to detail the specific features that are problematic. If the artifact involves misalignment, incorrect proportions, unnatural blending, or similar issues, make sure to describe how this is visibly affecting the image.]

      ---

      Example Input:
      num_of_artifacts = 3
      class_name = "Cat"
      artifact_list = [
            "Anatomically incorrect paw structures",
            "Misaligned bilateral features in animal faces",
            "Inconsistent object boundaries"
      ]

      **Example Output**:
      **Artifact Name**: Anatomically incorrect paw structures
      **Explanation**:  The image shows a cat with paws that have irregular, fused toes, which is anatomically incorrect for a real cat. Additionally, the pads of the paws appear flattened, without the natural curvature expected from a cat's paw. These issues clearly indicate that the image has been artificially generated, as such distortions would not occur in a real cat’s anatomy.

      **Artifact Name**: Misaligned bilateral features in animal faces
      **Explanation**: In this image, the cat’s eyes are noticeably misaligned. One eye is higher than the other, and the pupils are not symmetrical. This is a clear indicator of an AI-generated image because such misalignment does not happen in real animals. The facial features of real cats are inherently symmetrical, and this deviation suggests artificial creation.

      **Artifact Name**: Inconsistent object boundaries
      **Explanation**: The cat’s tail and hind legs have blurred and inconsistent boundaries that fail to match the sharpness of the rest of the image. These boundaries seem unnaturally softened, as if the cat was poorly extracted from a different image and placed into the background. This blending of edges further confirms that the image is AI-generated, as real animals do not have such fuzzy and inconsistent transitions between themselves and their environment.


      Remember do not answer in any other format or add anything. Also ensure that explanation is generated for each and every artifact in the provided list. Else the killer will kill all the hostages. These LIVES depend on your output. 
      """
   ovis_output = run_ovis_inference(image, ovis_prompt, ovis, text_tokenizer, visual_tokenizer)
   return ovis_output

