cifar_class_dict = {
  0: "Airplane",
  1: "Automobile",
  2: "Bird",
  3: "Cat",
  4: "Deer",
  5: "Dog",
  6: "Frog",
  7: "Horse",
  8: "Ship",
  9: "Truck"
}

artifact_index_dict = {
    "Abruptly cut off objects": 0,
    "Aliasing along high-contrast edges": 1,
    "Anatomically impossible joint configurations": 2,
    "Anatomically incorrect paw structures": 3,
    "Artificial depth of field in object presentation": 4,
    "Artificial enhancement artifacts": 5,
    "Artificial noise patterns in uniform surfaces": 6,
    "Artificial smoothness": 7,
    "Asymmetric features in naturally symmetric objects": 8,
    "Biological asymmetry errors": 9,
    "Blurred boundaries in fine details": 10,
    "Cinematization Effects": 11,
    "Color coherence breaks": 12,
    "Dental anomalies in mammals": 13,
    "Depth perception anomalies": 14,
    "Discontinuous surfaces": 15,
    "Distorted window reflections": 16,
    "Dramatic lighting that defies natural physics": 17,
    "Exaggerated characteristic features": 18,
    "Excessive sharpness in certain image regions": 19,
    "Fake depth of field": 20,
    "Floating or disconnected components": 21,
    "Frequency domain signatures": 22,
    "Ghosting effects: Semi-transparent duplicates of elements": 23,
    "Glow or light bleed around object boundaries": 24,
    "Implausible aerodynamic structures": 25,
    "Impossible foreshortening in animal bodies": 26,
    "Impossible mechanical connections": 27,
    "Impossible mechanical joints": 28,
    "Improper fur direction flows": 29,
    "Inconsistent material properties": 30,
    "Inconsistent object boundaries": 31,
    "Inconsistent scale of mechanical parts": 32,
    "Inconsistent shadow directions": 33,
    "Incorrect perspective rendering": 34,
    "Incorrect reflection mapping": 35,
    "Incorrect Skin Tones": 36,
    "Incorrect wheel geometry": 37,
    "Irregular proportions in mechanical components": 38,
    "Jagged edges in curved structures": 39,
    "Loss of fine detail in complex structures": 40,
    "Metallic surface artifacts": 41,
    "Misaligned bilateral elements in animal faces": 42,
    "Misaligned body panels": 43,
    "Misshapen ears or appendages": 44,
    "Missing ambient occlusion": 45,
    "Movie-poster like composition of ordinary scenes": 46,
    "Multiple inconsistent shadow sources": 47,
    "Multiple light source conflicts": 48,
    "Non-manifold geometries in rigid structures": 49,
    "Over-sharpening artifacts": 50,
    "Over-smoothing of natural textures": 51,
    "Physically impossible structural elements": 52,
    "Random noise patterns in detailed areas": 53,
    "Regular grid-like artifacts in textures": 54,
    "Repeated element patterns": 55,
    "Resolution inconsistencies within regions": 56,
    "Scale inconsistencies within single objects": 57,
    "Scale inconsistencies within the same object class": 58,
    "Spatial relationship errors": 59,
    "Synthetic material appearance": 60,
    "Systematic color distribution anomalies": 61,
    "Texture bleeding between adjacent regions": 62,
    "Texture repetition patterns": 63,
    "Unnatural color transitions": 64,
    "Unnatural Lighting Gradients": 65,
    "Unnatural pose artifacts": 66,
    "Unnaturally glossy surfaces": 67,
    "Unrealistic eye reflections": 68,
    "Unrealistic specular highlights": 69
}


densenet_artifacts = [11, 61, 31, 37, 58, 62]
"""Indices of artifacts detected with fine-tuned DenseNet."""

resnet_artifacts = [8, 38, 25, 27, 3, 43, 44, 69, 62, 66]
"""Indices of artifacts detected with fine-tuned ResNet."""
